name: OpenOCD EasyDevKits CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get install libudev-dev systemd --force-yes -y
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: linux

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get install libtool-bin libudev-dev gcc-mingw-w64-i686
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: windows
